[book]
authors = ["Ultiscore"]
language = "en"
src = "src"
title = "Ultiscore Documentation"

[output.html]
site-url = "/shenqjye93.mdbook.io/"
theme = "theme"
fold = { enable = true, level = 0}
favicon = "favicon.png"
additional-css = ["theme/custom.css"]
clean-urls = true

default-theme = "light"