[book]
authors = ["Ultiscore"]
language = "en"
src = "src"
title = "Ultiscore Documentation"

[output.html]
default-theme = "light"
preferred-dark-theme = "light"
clean-urls = true
theme = "theme"
fold = { enable = true, level = 0}
favicon = "favicon.png"
additional-css = ["theme/custom.css"]
